### PR TITLE
Login with GitHub

### PR DESCRIPTION
**Pull request by JingyuZ**
- show a login with github button on index page if there is no token stored in cookie
- click button takes user to authenticate with Github
- if authentication succeed, store the token (for future use to communicate with github) in cookie (TODO: we need a better way to handle this to avoid security issues), and update `loggedIn` state in store to be `true`
- do not render log in button if user has already logged in
- minor: also removed `@types/redux-thunk` warnings by removing the package

Note:
- I deployed a gatekeeper app on heroku to handle token exchange with Github, as we can't put `CLIENT_SECRECT` in Github public repo
- I introduced `reactrap` which based on `bootstrap` as a component library

TODO:
Github OAuth only supports one callback URL, but we need at least two for dev and pro environments. So I'm going to register another OAuth app for prod, and put the `PROD_CLIENT_ID` for authentication in production. But we need a public url and redirect url for production first...any ideas? any preference about what the URL should be?

### CODE REVIEW

**Review by m-roberts — APPROVED** [review]
LGTM

**Comment by m-roberts** [comment]
There should be a way to log out.

Do you have a suggestion for improving on storing in a cookie?

Can you put any information re: CLIENT_SECRET and the heroku app up on Slack? Is this an essential component? Does this mean that we can't be truly serverless?

Re: public url and redirect url for production, I'm not sure. What are our options?

**Comment by JingyuZ** [comment]
@m-roberts I posted the replies to your questions in slack

**Comment by JingyuZ** [comment]
Close #8 other than I put log in button on the home page right now, we can adjust after we get the UI mockup.

**Pull request merged**
